const novelMockData = [
  // ================= SÁNG TÁC =================
  {
    id: "st-1",
    title: "Nhân Vật Phản Diện Hạng Ba Muốn Được Sống Yên Bình",
    cover: "https://i2.hako.vip/ln/series/covers/s14076-8fdb808e-5d7f-4d92-9f62-e001768531b9.jpg",
    author: "Kachou Fuugetsu",
    artist: "Chưa cập nhật",
    anotherName: "The Hero Of Dark Fantasy Became The Third-Rate Villain In Romance Fantasy",
    description: "Phản diện hạng ba là cái thể loại nhân vật nền tồn tại để trở thành bao cát cho nhân vật chính thể hiện, cái thể loại mà chẳng ai thèm nhớ tên sau ba chương. Hắn đã chuyển sinh thành Schwarz Skywalker, một phản diện hạng ba như vậy. Mong muốn yên bình là điều quá xa xỉ sao? ",
    translatorGroup: "Tự Sáng Tác",
    uploader: "HakoAdmin",
    genres: ["Action", "Adventure", "Fantasy"],
    lastUpdated: "2 giờ trước",
    wordCount: "1.2M",
    rating: 4.8,
    views: "2.1M",
    chapter: "Chương 342",
    type: "sangtac",
    status: "ongoing",
    hue: 260
  },
  {
    id: "st-2",
    title: "Ultimate Senpai",
    cover: "https://i2.hako.vip/ln/series/covers/s26444-ff1577f6-531b-4f20-a631-e81ba3fdc953.jpg",
    author: "Vô Danh",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Câu chuyện về Senpai mạnh mẽ nhất.",
    translatorGroup: "Tự Sáng Tác",
    uploader: "User1",
    genres: ["School Life", "Comedy"],
    lastUpdated: "5 giờ trước",
    wordCount: "800K",
    rating: 4.7,
    views: "1.5M",
    chapter: "Chương 128",
    type: "sangtac",
    status: "ongoing",
    badge: "new",
    hue: 340
  },
  {
    id: "st-3",
    title: "Bản Ghi Chép Của Damonie",
    cover: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=400&auto=format&fit=crop",
    author: "Damonie",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Những ghi chép kỳ bí về thế giới ma thuật.",
    translatorGroup: "Tự Sáng Tác",
    uploader: "User2",
    genres: ["Fantasy", "Mystery"],
    lastUpdated: "1 ngày trước",
    wordCount: "450K",
    rating: 4.5,
    views: "900K",
    chapter: "Chương 50",
    type: "sangtac",
    status: "completed",
    badge: "",
    hue: 150
  },
  {
    id: "st-4",
    title: "Cuộc đời thứ hai của gã kiếm sĩ phiền phức",
    cover: "https://images.unsplash.com/photo-1605806616949-1e87b487cb2a?q=80&w=400&auto=format&fit=crop",
    author: "Kiếm Khách",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Trọng sinh làm lại cuộc đời trong tổ đội Anh Hùng.",
    translatorGroup: "Tự Sáng Tác",
    uploader: "User3",
    genres: ["Fantasy", "Action"],
    lastUpdated: "2 ngày trước",
    wordCount: "2.1M",
    rating: 4.9,
    views: "3.2M",
    chapter: "Chương 99",
    type: "sangtac",
    status: "ongoing",
    badge: "hot",
    hue: 45
  },
  {
    id: "st-5",
    title: "Dạ Điệp Quỷ Sát Ký",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=400&auto=format&fit=crop",
    author: "Nguyệt Dạ",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Hành trình diệt quỷ trong đêm tối.",
    translatorGroup: "Tự Sáng Tác",
    uploader: "User4",
    genres: ["Horror", "Action"],
    lastUpdated: "3 ngày trước",
    wordCount: "1.5M",
    rating: 4.6,
    views: "2.5M",
    chapter: "Chương 70",
    type: "sangtac",
    status: "completed",
    badge: "",
    hue: 200
  },
  {
    id: "st-6",
    title: "Hồi Ký Những Năm Tháng Ấy",
    cover: "https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?q=80&w=400&auto=format&fit=crop",
    author: "Thanh Xuân",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Ký ức về một thời thanh xuân tươi đẹp.",
    translatorGroup: "Tự Sáng Tác",
    uploader: "User5",
    genres: ["Romance", "Slice of Life"],
    lastUpdated: "1 tuần trước",
    wordCount: "600K",
    rating: 4.8,
    views: "1.8M",
    chapter: "Chương 45",
    type: "sangtac",
    status: "ongoing",
    badge: "new",
    hue: 10
  },
  {
    id: "st-7",
    title: "Sử ký Dahlia",
    cover: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?q=80&w=400&auto=format&fit=crop",
    author: "Sử Gia",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Biên niên sử về vương quốc Dahlia hùng mạnh.",
    translatorGroup: "Tự Sáng Tác",
    uploader: "User6",
    genres: ["Historical", "Fantasy"],
    lastUpdated: "2 tuần trước",
    wordCount: "3.2M",
    rating: 4.9,
    views: "4.1M",
    chapter: "Chương 210",
    type: "sangtac",
    status: "completed",
    badge: "hot",
    hue: 280
  },
  {
    id: "st-8",
    title: "Mạo Hiểm Giả Cấp Tối Đa",
    cover: "https://images.unsplash.com/photo-1528150232549-3bc05e548234?q=80&w=400&auto=format&fit=crop",
    author: "Max Level",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Bắt đầu chuyến phiêu lưu khi đã đạt cấp độ tối đa.",
    translatorGroup: "Tự Sáng Tác",
    uploader: "User7",
    genres: ["Action", "Adventure"],
    lastUpdated: "1 tháng trước",
    wordCount: "1.8M",
    rating: 4.7,
    views: "2.9M",
    chapter: "Chương 150",
    type: "sangtac",
    status: "ongoing",
    badge: "",
    hue: 180
  },

  // ================= TRUYỆN DỊCH =================
  {
    id: "td-1",
    title: "Nhân Vật Chính Trong Truyện Lãng Mạn Kỳ Ảo Chỉ Thích Mình Tôi",
    cover: "https://images.novelpia.com/imagebox/f1/f13d921146eed006f0f507238642d199_3455872_1751592719_ori.file",
    author: "Verbena",
    artist: "Chưa cập nhật",
    anotherName: "로판 속 주인공이 나만 좋아함",
    description: "Quý cô sa cơ Marigold, cho đến khi em hạnh phúc.",
    translatorGroup: "Aiko",
    uploader: "Aiko Shimizu",
    genres: ["Pure Love", "Romance", "Fantasy"],
    lastUpdated: "1 ngày",
    wordCount: "3.5M",
    rating: 4.9,
    views: "5M",
    chapter: "175. Hạnh Phúc Chắc Chắn Sẽ Đến",
    type: "truyendich",
    status: "completed",
    badge: "hot",
    hue: 220
  },
  {
    id: "td-2",
    title: "Overlord",
    cover: "https://images.unsplash.com/photo-1618331835717-801e976710b2?q=80&w=400&auto=format&fit=crop",
    author: "Kugane Maruyama",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Kẻ thống trị vĩ đại trong trò chơi xuyên không.",
    translatorGroup: "Yuri Alpha",
    uploader: "Ainz",
    genres: ["Fantasy", "Hành động", "Isekai"],
    lastUpdated: "1 tuần trước",
    wordCount: "2.5M",
    rating: 4.9,
    views: "4.5M",
    chapter: "Chương 156",
    type: "truyendich",
    status: "ongoing",
    badge: "",
    hue: 160
  },
  {
    id: "td-3",
    title: "Tensei Slime",
    cover: "https://images.unsplash.com/photo-1543332143-4e8c27e3256f?q=80&w=400&auto=format&fit=crop",
    author: "Fuse",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Xây dựng quốc gia ma vật từ một con Slime nhỏ bé.",
    translatorGroup: "Slime Group",
    uploader: "Rimuru",
    genres: ["Isekai", "Fantasy", "Comedy"],
    lastUpdated: "3 ngày trước",
    wordCount: "4M",
    rating: 4.8,
    views: "6M",
    chapter: "Chương 120",
    type: "truyendich",
    status: "ongoing",
    badge: "hot",
    hue: 300
  },
  {
    id: "td-4",
    title: "Re:Zero",
    cover: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=400&auto=format&fit=crop",
    author: "Tappei Nagatsuki",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Năng lực Trở Về Từ Cõi Chết.",
    translatorGroup: "Lugnica",
    uploader: "Subaru",
    genres: ["Isekai", "Psychological", "Drama"],
    lastUpdated: "2 tuần trước",
    wordCount: "5M",
    rating: 4.9,
    views: "5.5M",
    chapter: "Chương 80",
    type: "truyendich",
    status: "ongoing",
    badge: "",
    hue: 50
  },
  {
    id: "td-5",
    title: "KonoSuba",
    cover: "https://images.unsplash.com/photo-1605806616949-1e87b487cb2a?q=80&w=400&auto=format&fit=crop",
    author: "Natsume Akatsuki",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Cuộc sống tuyệt vời ở thế giới khác... hay không?",
    translatorGroup: "Aqua Fanclub",
    uploader: "Kazuma",
    genres: ["Comedy", "Isekai"],
    lastUpdated: "1 tháng trước",
    wordCount: "2.8M",
    rating: 4.8,
    views: "3.5M",
    chapter: "Chương 100",
    type: "truyendich",
    status: "completed",
    badge: "hot",
    hue: 90
  },
  {
    id: "td-6",
    title: "Sword Art Online",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=400&auto=format&fit=crop",
    author: "Reki Kawahara",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Trò chơi tử thần.",
    translatorGroup: "Aincrad",
    uploader: "Kirito",
    genres: ["Sci-fi", "Action", "Romance"],
    lastUpdated: "2 tháng trước",
    wordCount: "4.2M",
    rating: 4.7,
    views: "7M",
    chapter: "Chương 250",
    type: "truyendich",
    status: "ongoing",
    badge: "",
    hue: 20
  },
  {
    id: "td-7",
    title: "No Game No Life",
    cover: "https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?q=80&w=400&auto=format&fit=crop",
    author: "Yuu Kamiya",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Thế giới được quyết định bằng trò chơi.",
    translatorGroup: "Blank",
    uploader: "Sora",
    genres: ["Fantasy", "Comedy"],
    lastUpdated: "3 tháng trước",
    wordCount: "1.9M",
    rating: 4.9,
    views: "2.4M",
    chapter: "Chương 60",
    type: "truyendich",
    status: "completed",
    badge: "new",
    hue: 190
  },
  {
    id: "td-8",
    title: "Thiên Sứ Nhà Bên",
    cover: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?q=80&w=400&auto=format&fit=crop",
    author: "Saeki-san",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Câu chuyện tình cảm ngọt ngào với cô hàng xóm.",
    translatorGroup: "Romcom VN",
    uploader: "Amane",
    genres: ["Romance", "Slice of Life"],
    lastUpdated: "1 ngày trước",
    wordCount: "1.1M",
    rating: 4.8,
    views: "1.9M",
    chapter: "Chương 45",
    type: "truyendich",
    status: "ongoing",
    badge: "hot",
    hue: 130
  },

  // ================= AI DỊCH =================
  {
    id: "ai-1",
    title: "Solo Leveling",
    cover: "https://images.unsplash.com/photo-1528150232549-3bc05e548234?q=80&w=400&auto=format&fit=crop",
    author: "Chugong",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Thợ săn hạng E chật vật sinh tồn trong hầm ngục nguy hiểm.",
    translatorGroup: "AI Dịch Lỏ",
    uploader: "Bot",
    genres: ["Hành động", "Fantasy", "Hàn Quốc"],
    lastUpdated: "10 phút trước",
    wordCount: "800K",
    rating: 4.5,
    views: "3.2M",
    chapter: "Chương 270",
    type: "aidich",
    status: "completed",
    badge: "AI",
    hue: 45
  },
  {
    id: "ai-2",
    title: "Omniscient Reader",
    cover: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?q=80&w=400&auto=format&fit=crop",
    author: "Sing Shong",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Chỉ mình ta biết kết cục của thế giới này.",
    translatorGroup: "AI Dịch Lỏ",
    uploader: "Bot",
    genres: ["Fantasy", "Sinh tồn"],
    lastUpdated: "30 phút trước",
    wordCount: "2M",
    rating: 4.9,
    views: "3.8M",
    chapter: "Chương 551",
    type: "aidich",
    status: "ongoing",
    badge: "AI",
    hue: 200
  },
  {
    id: "ai-3",
    title: "The Beginning After The End",
    cover: "https://images.unsplash.com/photo-1618331835717-801e976710b2?q=80&w=400&auto=format&fit=crop",
    author: "TurtleMe",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Vị vua chuyển sinh thành Arthur Leywin.",
    translatorGroup: "AI Dịch Lỏ",
    uploader: "Bot",
    genres: ["Fantasy", "Isekai"],
    lastUpdated: "1 giờ trước",
    wordCount: "1.5M",
    rating: 4.8,
    views: "2.9M",
    chapter: "Chương 112",
    type: "aidich",
    status: "ongoing",
    badge: "AI",
    hue: 110
  },
  {
    id: "ai-4",
    title: "Lord of the Mysteries",
    cover: "https://images.unsplash.com/photo-1543332143-4e8c27e3256f?q=80&w=400&auto=format&fit=crop",
    author: "Cuttlefish That Loves Diving",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Một thế giới Steampunk với những bí ẩn của các Vị Thần.",
    translatorGroup: "AI Dịch Lỏ",
    uploader: "Bot",
    genres: ["Mystery", "Fantasy"],
    lastUpdated: "5 giờ trước",
    wordCount: "4.5M",
    rating: 4.9,
    views: "6M",
    chapter: "Chương 800",
    type: "aidich",
    status: "ongoing",
    badge: "AI",
    hue: 250
  },
  {
    id: "ai-5",
    title: "Reverend Insanity",
    cover: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=400&auto=format&fit=crop",
    author: "Gu Zhen Ren",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Nhân vật phản diện tàn nhẫn truy cầu trường sinh.",
    translatorGroup: "AI Dịch Lỏ",
    uploader: "Bot",
    genres: ["Xianxia", "Action"],
    lastUpdated: "1 ngày trước",
    wordCount: "6.2M",
    rating: 4.8,
    views: "5.5M",
    chapter: "Chương 400",
    type: "aidich",
    status: "ongoing",
    badge: "AI",
    hue: 320
  },
  {
    id: "ai-6",
    title: "Shadow Hack",
    cover: "https://images.unsplash.com/photo-1605806616949-1e87b487cb2a?q=80&w=400&auto=format&fit=crop",
    author: "Bạo Táo Đích Kiết Tử",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Hệ thống hack vô đối.",
    translatorGroup: "AI Dịch Lỏ",
    uploader: "Bot",
    genres: ["Sci-fi", "Action"],
    lastUpdated: "2 ngày trước",
    wordCount: "2.1M",
    rating: 4.6,
    views: "1.2M",
    chapter: "Chương 55",
    type: "aidich",
    status: "ongoing",
    badge: "AI",
    hue: 60
  },
  {
    id: "ai-7",
    title: "Library of Heaven's Path",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=400&auto=format&fit=crop",
    author: "Heng Shao Tian Ya",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Thư viện chứa mọi tri thức trên đời.",
    translatorGroup: "AI Dịch Lỏ",
    uploader: "Bot",
    genres: ["Xianxia", "Comedy"],
    lastUpdated: "3 ngày trước",
    wordCount: "7M",
    rating: 4.7,
    views: "4.8M",
    chapter: "Chương 1000",
    type: "aidich",
    status: "ongoing",
    badge: "AI",
    hue: 140
  },
  {
    id: "ai-8",
    title: "Super Gene",
    cover: "https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?q=80&w=400&auto=format&fit=crop",
    author: "Twelve Winged Dark Seraphim",
    artist: "Chưa cập nhật",
    anotherName: "Không có",
    description: "Tiến hóa thông qua gen di truyền.",
    translatorGroup: "AI Dịch Lỏ",
    uploader: "Bot",
    genres: ["Sci-fi", "Fantasy"],
    lastUpdated: "4 ngày trước",
    wordCount: "10M",
    rating: 4.9,
    views: "8.2M",
    chapter: "Chương 2100",
    type: "aidich",
    status: "completed",
    badge: "AI",
    hue: 15
  }
];

function generateNovelCardHTML(novel) {
  return `
    <article class="novel-card" data-novel-id="${novel.id}" data-novel-type="${novel.type}">
      <div class="novel-cover" style="--hue: ${novel.hue || 200};">
        <div class="cover-art" style="background-image: url('${novel.cover}'); background-size: cover; background-position: center;"></div>
      </div>
      <div class="novel-info">
        <h3 class="novel-title">${novel.title}</h3>
        <p class="novel-chapter">${novel.chapter}</p>
      </div>
    </article>
  `;
}

function renderNovelsToDOM() {
  // Lọc truyện theo loại
  const sangtacNovels = novelMockData.filter(n => n.type === 'sangtac');
  const truyendichNovels = novelMockData.filter(n => n.type === 'truyendich');
  const aidichNovels = novelMockData.filter(n => n.type === 'aidich');

  // Hàm render grid
  const renderGrid = (selector, novels) => {
    const grids = document.querySelectorAll(selector);
    grids.forEach(grid => {
      if (grid) {
        grid.innerHTML = novels.map(n => generateNovelCardHTML(n)).join('');
      }
    });
  };

  // Cập nhật các section grid chung trong tab Toàn Bộ
  renderGrid('#home-content-toanbo .novel-section[data-section-type="sangtac"] .novel-grid', sangtacNovels);
  renderGrid('#home-content-toanbo .novel-section[data-section-type="truyendich"] .novel-grid', truyendichNovels);
  renderGrid('#home-content-toanbo .novel-section[data-section-type="aidich"] .novel-grid', aidichNovels);

  // Cập nhật các grid ở các tab Sáng tác, Truyện dịch, AI dịch
  renderGrid('#home-content-sangtac .novel-grid', sangtacNovels);
  renderGrid('#home-content-truyendich .novel-grid', truyendichNovels);
  renderGrid('#home-content-aidich .novel-grid', aidichNovels);
}

// Chạy trực tiếp thay vì chờ DOMContentLoaded
// Vì script này được đặt ở cuối thẻ <body>
renderNovelsToDOM();
